name: Testing Spring Boot Code On Github Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "success"
