name: Testing Spring Boot Code On Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      #Java 17の環境を構築(インストール)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      #Gradleのバッチに実行権限付与(デフォルトでは実行権限がない)
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      #ビルドして単体テストレポート出力(Jacoco)
      - name: Build with Gradle(Jacoco)
        run: ./gradlew build jacocoTestReport
